# Generated by Django 4.2.7 on 2026-07-13 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0003_remove_unique_documento_identidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaCanaston',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_inicio_calculo', models.DateField(help_text='Fecha inicio para cálculo de rendimiento')),
                ('fecha_fin_calculo', models.DateField(help_text='Fecha fin para cálculo de rendimiento')),
                ('fecha_entrega', models.DateField(blank=True, help_text='Fecha prevista para entrega de canastones', null=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Campaña de Canastón',
                'verbose_name_plural': 'Campañas de Canastón',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pago',
            name='adelantos_totales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de adelantos (deudas) aprobados', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='neto_pagar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='salario_base - descuentos_totales - adelantos_totales', max_digits=10),
        ),
        migrations.CreateModel(
            name='ResultadoCanaston',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_lealtad_snapshot', models.IntegerField(help_text='Score de lealtad al momento del cálculo')),
                ('porcentaje_asistencia_snapshot', models.DecimalField(decimal_places=2, help_text='Porcentaje de asistencia en el período', max_digits=5)),
                ('es_elegible', models.BooleanField(default=False, help_text='Cumple con los requisitos para recibir canastón')),
                ('estado_entrega', models.CharField(choices=[('PENDIENTE', 'Pendiente de Entrega'), ('ENTREGADO', 'Entregado'), ('NO_ELEGIBLE', 'No Elegible')], default='PENDIENTE', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='gestion_banda.campanacanaston')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_canaston', to='gestion_banda.musico')),
            ],
            options={
                'verbose_name': 'Resultado de Canastón',
                'verbose_name_plural': 'Resultados de Canastón',
                'ordering': ['-score_lealtad_snapshot'],
                'unique_together': {('campana', 'musico')},
            },
        ),
    ]
