# Generated by Django 4.2.7 on 2026-07-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_banda", "0004_campanacanaston_alter_pago_adelantos_totales_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="seccion_encargada",
            field=models.CharField(
                blank=True,
                help_text="Sección asignada para Jefe de Sección",
                max_length=50,
                null=True,
            ),
        ),
    ]
