# Generated by Django 4.2.7 on 2026-07-20 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0005_usuario_seccion_encargada'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='responsables_pago',
            field=models.ManyToManyField(blank=True, related_name='eventos_a_pagar', to=settings.AUTH_USER_MODEL),
        ),
    ]
