# Generated by Django 4.2.7 on 2026-07-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0006_evento_responsables_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='evento',
            field=models.ForeignKey(blank=True, help_text='Evento o contrato en el que ocurrió la falta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='gestion_banda.evento'),
        ),
    ]
