# Generated by Django 4.2.7 on 2026-07-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0007_descuento_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='responsables_pago',
        ),
    ]
