# Generated by Django 4.2.7 on 2026-07-21 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0008_remove_evento_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
