# Generated by Django 4.2.7 on 2026-07-21 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0009_descuento_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
