# Generated by Django 4.2.7 on 2026-07-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0010_alter_descuento_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='titulo_contrato',
            field=models.CharField(blank=True, help_text='Título general del contrato', max_length=200, null=True),
        ),
    ]
