# Generated by Django 4.2.7 on 2026-07-29 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0011_evento_titulo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillaliquidacion',
            name='origen',
            field=models.CharField(choices=[('APP_MOVIL', 'App Móvil'), ('FRONTEND', 'Frontend')], default='FRONTEND', max_length=20),
        ),
        migrations.AddField(
            model_name='planillaliquidacion',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_registradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
