# Generated by Django 4.2.7 on 2026-07-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0012_planillaliquidacion_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='clave',
            field=models.CharField(choices=[('DASHBOARD', 'Dashboard Principal'), ('MUSICOS', 'Gestión de Músicos'), ('EVENTOS', 'Gestión de Eventos'), ('DESCUENTOS', 'Registrar Descuentos'), ('ADELANTOS', 'Registrar Adelantos'), ('LIQUIDACIONES', 'Generar Liquidaciones'), ('CANASTON', 'Canastón - Rendimiento'), ('FINANCIAMIENTO', 'Financiamiento'), ('HISTORIAL_DESCUENTOS', 'Ver Historial de Descuentos'), ('HISTORIAL_CONTRATOS', 'Ver Historial de Contratos'), ('ADMIN_USUARIOS', 'Administración de Usuarios'), ('MI_RESUMEN', 'Mi Resumen Financiero')], max_length=50, unique=True),
        ),
    ]
