# Generated by Django 4.2.7 on 2026-07-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0013_alter_modulo_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pin_actual',
            field=models.CharField(blank=True, help_text='Almacena el PIN en texto plano solo para visibilidad del Presidente', max_length=4, null=True),
        ),
    ]
