# Generated by Django 4.2.7 on 2026-07-30 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0014_usuario_pin_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='origen',
            field=models.CharField(blank=True, choices=[('APP_MOVIL', 'App Móvil'), ('FRONTEND', 'Frontend')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
