# Generated by Django 6.0.3 on 2026-08-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banda', '0015_pago_origen_pago_registrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='uniforme',
            field=models.CharField(choices=[('GALA', 'Uniforme de Gala'), ('NEGRO', 'Uniforme Negro'), ('DIANA', 'Uniforme de Diana'), ('DIARIO', 'Uniforme Diario'), ('VIAJE', 'Uniforme de Viaje'), ('VELADA', 'Uniforme de Velada'), ('OTRO', 'Otro (especificar)')], default='DIARIO', max_length=20),
        ),
    ]
